name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 * * * *'
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: athul/waka-readme@e96e0f6d9763fa44245fe1f6736c1d2d4e5d4e3f # master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }},
          SHOW_TITLE: true
          BLOCKS: =>
          TIME_RANGE: all_time
          LANG_COUNT: 42069
          SHOW_TIME: true
          SHOW_TOTAL: true
          STOP_AT_OTHER: false
          COMMIT_MESSAGE: Updated waka-readme :)
          AUTHOR_NAME: h4rldev
